server:
  port: 8080
  servlet:
    session:
      cookie:
        max-age=-1s:

#  配置mapper位置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

#  配置数据源
spring:
  datasource:
    druid:
      url: jdbc:mysql://oopsw.top:3306/blog?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
      username: root
      password: wsy112233
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 10000
      testOnBorrow: true
      testOnReturn: false
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  data:
    # 配置mongodb
    mongodb:
      host: oopsw.top
      database: blog
  redis:
    host: oopsw.top
    port: 6379
#配置分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: false #pageSize=0
  params: count=countSql

#配置七牛云对象存储
upload:
  base-url: http://808km.top/
  access-key: 5-U8eZh2aa1zVv9fENG1TrZ8mTcX5OKYjvpreVBN
  secret-key: SIcqae8SXsHfab7kEbjfSw1oCCWcxRq4v5SmzV-G
  bucket: oopsw
  picture-prefix: blog/img/

