server:
  port: 8080
  servlet:
    session:
      cookie:
        max-age=-1s:

#  配置mapper位置
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml

#  配置数据源
spring:
  datasource:
    druid:
      url: jdbc:mysql://112.74.99.109:3306/blog?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
      username: root
      password: wsy112233
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 10000
      testOnBorrow: true
      testOnReturn: false
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  data:
    # 配置mongodb
    mongodb:
      host: 112.74.99.109
      database: blog
  redis:
    host: 112.74.99.109
    port: 6379

fdfs:
  so-timeout: 2500
  connect-timeout: 600
  thumb-image:
    width: 100
    height: 100
  tracker-list:
    - 112.74.99.109:22122
upload:
  base-url: http://112.74.99.109/
  allow-types:
    - image/jpeg
    - image/png
    - image/bmp
    - image/gif
    - audio/mpeg


#配置分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: false #pageSize=0
  params: count=countSql
